language: ruby
rvm:
  - 2.5.6
services:
  - docker
env:
  matrix:
    - CHEF_VERSION=12
    - CHEF_VERSION=13
    - CHEF_VERSION=14
    - CHEF_VERSION=15
script:
  - bundle exec rake
  - bundle exec rake test:kitchen
